### PR TITLE
fix exception if mzml chromatograms with 0 data points were imported

### LINKED ISSUE #2262: New mzmine 4.4.0 issue: stop the processing
mzmine 4.4 constantly crashes.

My operating system and version: Windows 64x 
My mzmine version: 4.4.0

When using the newer version for an old project, I could not open the previous project, so I decided to reprocess it. However, the process is continuously stopped, and we cannot proceed. Please take a look at the log file below. We use the mzwizard UHPLC-QTOF default parameters. The same mzML files were previously processed by mzmine. 

2024-11-27 15:20:31 WARNING io.github.mzmine.main.impl.MZmineConfigurationImpl getModuleParameters Module class io.github.mzmine.modules.tools.batchwizard.BatchWizardModule does not provide any ParameterSet class

2024-11-27 15:23:16 WARNING io.github.mzmine.project.impl.RawDataFileImpl addScan Some MS1 scans were recognized as empty (no detected peaks).
3:17 FINEST io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask parseMzMlInternal Parsing Complete
2024-11-27 15:23:17 WARNING io.github.mzmine.project.impl.RawDataFileImpl addScan Some MS1 scans were recognized as empty (no detected peaks).

2024-11-27 15:23:22 WARNING io.github.mzmine.project.impl.RawDataFileImpl addScan Some MS1 scans were recognized as empty (no detected peaks).
2024-11-27 15:23:22 FINEST io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask parseMzMlInternal Parsing Complete
2024-11-27 15:23:22 INFO   io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask importStreamOrFile Finished parsing C:\Metabolomics\mzMINE\MC\Macrophages_ESIpos\mzMLmzML_ESIpos\ESIpos_G5_021.mzML, parsed 17434 scans
2024-11-27 15:23:22 WARNING io.github.mzmine.project.impl.RawDataFileImpl addScan Some MS1 scans were recognized as empty (no detected peaks).

2024-11-27 15:23:22 WARNING io.github.mzmine.project.impl.RawDataFileImpl addScan Some MS1 scans were recognized as empty (no detected peaks).

2024-11-27 15:23:23 WARNING io.github.mzmine.project.impl.RawDataFileImpl addScan Some MS1 scans were recognized as empty (no detected peaks).

2024-11-27 15:23:28 FINEST io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask parseMzMlInternal Parsing Complete
2024-11-27 15:23:28 WARNING io.github.mzmine.project.impl.RawDataFileImpl addScan Some MS1 scans were recognized as empty (no detected peaks).

2024-11-27 15:23:28 INFO   io.github.mzmine.modules.io.import_rawdata_mzml.msdk.data.MzMLParser processOpeningTag startTimeStamp wasn't set
2024-11-27 15:23:28 FINEST io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask parseMzMlInternal Parsing Complete
2024-11-27 15:23:29 WARNING io.github.mzmine.project.impl.RawDataFileImpl addScan Some MS1 scans were recognized as empty (no detected peaks).

2024-11-27 15:23:29 WARNING io.github.mzmine.project.impl.RawDataFileImpl addScan Some MS1 scans were recognized as empty (no detected peaks).

2024-11-27 15:23:29 WARNING io.github.mzmine.project.impl.RawDataFileImpl addScan Some MS1 scans were recognized as empty (no detected peaks).

2024-11-27 15:23:38 WARNING io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask importStreamOrFile Error during mzML read: Out of bound access on segment MemorySegment{ heapBase: [D@2c447e3c, address: 0x0, byteSize: 0 }; new offset = -8; new length = 8
java.lang.IndexOutOfBoundsException: Out of bound access on segment MemorySegment{ heapBase: [D@2c447e3c, address: 0x0, byteSize: 0 }; new offset = -8; new length = 8
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.outOfBoundException(AbstractMemorySegmentImpl.java:434)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.apply(AbstractMemorySegmentImpl.java:415)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.apply(AbstractMemorySegmentImpl.java:70)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:124)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:448)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.checkBounds(AbstractMemorySegmentImpl.java:404)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.checkAccess(AbstractMemorySegmentImpl.java:364)
	at java.base/java.lang.invoke.VarHandleSegmentAsDoubles.checkAddress(VarHandleSegmentAsDoubles.java:88)
	at java.base/java.lang.invoke.VarHandleSegmentAsDoubles.get(VarHandleSegmentAsDoubles.java:114)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.getAtIndex(AbstractMemorySegmentImpl.java:935)
	at io.github.mzmine.datamodel.featuredata.IntensitySeries.getIntensity(IntensitySeries.java:93)
	at io.github.mzmine.datamodel.featuredata.FeatureDataUtils.recalculateIntensityTimeSeriesDependingTypes(FeatureDataUtils.java:288)
	at io.github.mzmine.datamodel.otherdetectors.OtherFeatureImpl.<init>(OtherFeatureImpl.java:45)
	at io.github.mzmine.modules.io.import_rawdata_mzml.ConversionUtils.convertOtherTraces(ConversionUtils.java:408)
	at io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask.importStreamOrFile(MSDKmzMLImportTask.java:225)
	at io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask.run(MSDKmzMLImportTask.java:163)
	at io.github.mzmine.taskcontrol.impl.WrappedTask.run(WrappedTask.java:169)
	at io.github.mzmine.taskcontrol.threadpools.ThreadPoolTask.lambda$trackProgressTask$3(ThreadPoolTask.java:183)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

2024-11-27 15:23:38 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing data: Subtask had an error or was interrupted
2024-11-27 15:23:38 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing raw data file: QC_FS_Pos_02_007.mzML: Unspecified error in class io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask
2024-11-27 15:23:38 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing raw data file: QC_Pos_03_015.mzML: Unspecified error in class io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask
2024-11-27 15:23:38 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing QC_Inc_Pos_02_009.mzML, total / parsed is 7336 / 5265: Unspecified error in class io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask
2024-11-27 15:23:38 WARNING io.github.mzmine.project.impl.RawDataFileImpl addScan Some MS1 scans were recognized as empty (no detected peaks).
2024-11-27 15:23:38 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing raw data file: QC_FS_Pos_01_006.mzML: Unspecified error in class io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask
2024-11-27 15:23:38 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing raw data file: QC_Inc_Pos_03_010.mzML: Unspecified error in class io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask
2024-11-27 15:23:38 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing raw data file: QC_Pos_02_006.mzML: Unspecified error in class io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask
2024-11-27 15:23:38 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing QC_Pos_01_005.mzML, total / parsed is 17495 / 16299: Unspecified error in class io.github.mzmine.modules.io.import_rawdata_mzml.MSDKmzMLImportTask
2024-11-27 15:23:38 WARNING io.github.mzmine.modules.batchmode.BatchTask run Subtask had an error or was interrupted
2024-11-27 15:23:38 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Batch step 2/19: Subtask had an error or was interrupted
2024-11-27 15:23:38 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing QC_Inc_Pos_01_008.mzML, total / parsed is 7514 / 7514: Error parsing mzML: java.lang.IndexOutOfBoundsException: Out of bound access on segment MemorySegment{ heapBase: [D@2c447e3c, address: 0x0, byteSize: 0 }; new offset = -8; new length = 8 (AbstractMemorySegmentImpl.java:434)

:) thanks

### PR DESCRIPTION
**Pull request by SteffenHeu**
fixes #2262

### CODE REVIEW

File: mzmine-community/src/main/java/io/github/mzmine/modules/io/import_rawdata_mzml/ConversionUtils.java [hunk 1]
```diff
@@ -401,6 +401,14 @@ public static List<OtherDataFile> convertOtherTraces(RawDataFile file,
         otherFile.setDescription(unit + "_" + chromType.getDescription());
 
         for (MzMLChromatogram chrom : unitChromEntry.getValue()) {
+          if (chrom.getNumberOfDataPoints() == 0) {
+            // drop empty chromatograms
+            logger.finest(
+                () -> "%s: Zero data points detected for chromatogram %s. Dropping".formatted(
```
Comment (robinschmid) [inline mzmine-community/src/main/java/io/github/mzmine/modules/io/import_rawdata_mzml/ConversionUtils.java:407]: Maybe also write what implications this has. 
This could also be an MRM chromatogram that is dropped?
Would this make issues downstream in the processing due to missing chromatogram?
